name: Windows

on:
  push:
    branches:
      - master
      - feature/fix-builds
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git pkgconf mingw-w64-x86_64-{cmake,SDL2,qt6-static,libarchive,toolchain,pcre2,libpng,harfbuzz}

    - name: Configure
      working-directory: ${{runner.workspace}}
      run: cmake -B build $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=ON -DUSE_QT6=ON -DCMAKE_PREFIX_PATH=C:/tools/msys64/mingw64/qt6-static

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build .
    
    - name: Preparing artifacts
      working-directory: ${{runner.workspace}}/build
      run: |
        mv melonDS.exe ./MelonMix.exe
        echo "MelonMix.exe -f roms/days.nds"    > ./MelonMix_KHDays.bat
        echo "MelonMix.exe -f roms/recoded.nds" > ./MelonMix_KHReCoded.bat

    - uses: actions/upload-artifact@v4
      with:
        name: MelonMix-windows-x86_64
        path: |
          ${{runner.workspace}}\build\MelonMix.exe
          ${{runner.workspace}}\build\MelonMix_KHDays.bat
          ${{runner.workspace}}\build\MelonMix_KHReCoded.bat
